# Configuración de la conexión a MySQL en XAMPP (Puerto 3307)
spring.datasource.url=jdbc:mysql://127.0.0.1/crm_animal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=


# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


# Configuración de Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ignacio.alvarezet32@gmail.com
spring.mail.password=tu-contrasena-de-aplicacion-de-16-caracteres
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true